[global]
threads = 1
repeat = 5
klen = 8
vlen = 16
kmin = 0
kmax = 1000000
report = "repeat"

[[benchmark]]
set_perc = 100
repeat = 1
dist = "incrementp"
report = "hidden"

# write-intensive, zipfian
[[benchmark]]
set_perc = 50
get_perc = 50
timeout = 1.0
dist = "zipfian"

# write-intensive, zipfian, hotspot in middle
[[benchmark]]
set_perc = 50
get_perc = 50
timeout = 1.0
dist = "zipfian"
zipf_hotspot = 0.5

# read-intensive, zipfian
[[benchmark]]
set_perc = 5
get_perc = 95
timeout = 1.0
dist = "zipfian"

# read-only, uniform
[[benchmark]]
get_perc = 100
timeout = 1.0
dist = "uniform"
