[global]
threads = 8
repeat = 5
klen = 8
vlen = 16
kmin = 0
kmax = 1000

[[benchmark]]
set_perc = 100
repeat = 1
dist = "incrementp"
report = "hidden"

[[benchmark]]
timeout = 1.0
set_perc = 50
get_perc = 50
dist = "zipfian"
report = "repeat"

[[benchmark]]
timeout = 1.0
set_perc = 50
get_perc = 50
dist = "uniform"
report = "repeat"
