name: test

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
    - uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-hack
    - name: build
      run: |
        cargo build --verbose --release
        cargo build --verbose --release --all-features
    - name: test
      run: |
        cargo test --release
        cargo hack test --each-feature --release
        cargo test --release --all-features
