[global]
threads = 8
repeat = 5
qd = 100
batch = 10
scan_n = 10
klen = 8
vlen = 16
kmin = 0
kmax = 10000

[[benchmark]]
set_perc = 100
repeat = 1
dist = "incrementp"

[[benchmark]]
timeout = 0.2
set_perc = 50
get_perc = 25
scan_perc = 25
dist = "zipfian"

[[benchmark]]
timeout = 0.2
set_perc = 50
get_perc = 25
scan_perc = 25
dist = "uniform"
